'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const puppeteer = require('puppeteer-core');
const base = 'http://127.0.0.1:8765/assets/demo-mobile/index.html';
const out = path.join(__dirname,'live_shots','android-demo');
fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await puppeteer.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,defaultViewport:{width:440,height:900}});
 const page=await browser.newPage(), errors=[],requests=[];
 page.on('pageerror',e=>errors.push(e.message));
 page.on('request',r=>requests.push(r.url()));
 const shot=name=>page.screenshot({path:path.join(out,name+'.png'),fullPage:true});
 const state=()=>page.evaluate(()=>MIB_MOBILE_DEMO.state);
 try {
  await page.goto(base);
  assert(await page.$eval('header',e=>getComputedStyle(e).display==='none'));
  await shot('01-login');
  await page.click('#mobile-login');
  assert.equal((await state()).view,'login');
  await page.type('#mobile-user','8546951251');await page.type('#mobile-password','demo123');await page.click('#mobile-login');
  assert.equal((await state()).view,'otp');await shot('02-otp-simulation');
  await page.type('#mobile-otp','123456');await page.click('#verify-otp');await shot('03-dashboard');
  await page.click('#mobile-back');await page.click('#employee-attendance');await shot('04-attendance');
  await page.click('#attendance-logout');assert.equal((await state()).view,'attendance');
  await page.click('#attendance-login');await page.click('#submit-selfie');
  await page.click('#attendance-logout');await page.click('#submit-selfie');
  assert((await state()).login&&(await state()).logout);await shot('05-attendance-completed');
  console.log('PASS sample login, OTP, attendance order, selfie placeholders and times');
  await page.goto(base+'?screen=tickets');await shot('06-tickets');await page.click('#sample-ticket');await shot('07-ticket-detail');
  await page.click('#ticket-menu');await page.click('#update-ticket-option');assert.equal((await state()).view,'detail');
  await page.click('#start-ticket-option');await page.type('#start-remark','Starting Work');await shot('08-start-simulation');await page.click('#start-ticket-submit');
  await page.click('#ticket-menu');await page.click('#update-ticket-option');
  await page.type('#ticket-review','Service done');await page.type('#ticket-description','General pest management service completed.');
  await page.select('#ticket-work-type','Service');await page.select('#ticket-status','Resolved');await page.click('#work-photo');await shot('09-update-simulation');
  await page.click('#update-submit');await page.click('#submit-ticket');assert.equal((await state()).view,'signature');
  await page.click('#add-signature');await shot('10-signature-simulation');await page.click('#submit-ticket');
  const completed=await state();assert.equal(completed.status,'Resolved');assert(completed.photo&&completed.signed&&completed.started);await shot('11-resolved-detail');
  await page.click('#mobile-back');await page.click('#tile-ticket');await page.click('#tab-resolved');assert(await page.$('#sample-ticket'));
  await page.click('#tab-pending');assert.equal(await page.$('#sample-ticket'),null);
  await page.click('#add-ticket');await shot('12-add-ticket');await page.click('#new-submit');assert((await page.$eval('#message',e=>e.textContent)).includes('No record was saved'));
  await page.goto(base+'?screen=tickets');assert.equal((await state()).status,'Open');
  console.log('PASS ticket start/update/signature, resolved tab, practice form and fresh replay reset');
  const external=requests.filter(url=>/^https?:/.test(url)&&!url.startsWith('http://127.0.0.1:8765/'));
  assert.deepEqual(external,[]);
  assert.deepEqual(errors,[]);
  const body=await page.$eval('body',e=>e.textContent);assert(!/TradeIndia|EpochElectric|Customer Call Analytics/.test(body));
  console.log('PASS no external requests, no copied live ticket titles, no JavaScript errors');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
